(() => {
  'use strict';
  const $ = s => document.querySelector(s);
  const make = (tag, cls, text) => { const n = document.createElement(tag); if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n; };
  let userMoved = false;
  ['wheel', 'touchstart', 'pointerdown', 'keydown'].forEach(type => addEventListener(type, () => { userMoved = true; }, { once: true, passive: true }));
  function settleInitialAnchor() {
    if (!location.hash || userMoved) return;
    document.fonts.ready.then(() => requestAnimationFrame(() => {
      if (userMoved) return;
      let id; try { id = decodeURIComponent(location.hash.slice(1)); } catch { return; }
      document.getElementById(id)?.scrollIntoView({ behavior: 'instant' });
    }));
  }
  document.querySelectorAll('[data-v2-year]').forEach(n => n.textContent = new Date().getFullYear());
  const menu=$('#v2-menu'), menuOpen=$('[data-menu-open]');
  if(menu){menuOpen.addEventListener('click',()=>{menu.showModal();document.body.classList.add('modal-open');});$('[data-menu-close]').addEventListener('click',()=>menu.close());menu.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>menu.close()));menu.addEventListener('close',()=>{document.body.classList.remove('modal-open');menuOpen.focus({preventScroll:true});});}
  const lightbox=$('#v2-lightbox');let previousFocus;
  function openImage(button){previousFocus=button;$('#v2-lightbox-image').src=button.dataset.src;$('#v2-lightbox-image').alt=button.dataset.title;$('#v2-lightbox-title').textContent=button.dataset.title;$('#v2-lightbox-caption').textContent=button.dataset.caption||'';lightbox.showModal();document.body.classList.add('modal-open');}
  if(lightbox){document.addEventListener('click',e=>{const b=e.target.closest('[data-v2-image]');if(b)openImage(b);});$('[data-lightbox-close]').addEventListener('click',()=>lightbox.close());lightbox.addEventListener('click',e=>{if(e.target!==lightbox)return;const r=lightbox.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)lightbox.close();});lightbox.addEventListener('close',()=>{document.body.classList.remove('modal-open');$('#v2-lightbox-image').removeAttribute('src');previousFocus?.focus({preventScroll:true});});}
  function imageButton(src,title,caption,cls,width,height){const b=make('button',cls);b.type='button';b.dataset.v2Image='';b.dataset.src=src;b.dataset.title=title;b.dataset.caption=caption;b.setAttribute('aria-label','放大查看：'+title);const img=make('img');img.src=src;img.alt=title;img.loading='lazy';if(width)img.width=width;if(height)img.height=height;b.append(img);return b;}
  const photos=$('#v2-photo-grid');
  if(photos)for(const p of window.PORTFOLIO_CONTENT?.photos||[]){const item=make('article');const b=imageButton(p.image,p.title,p.caption,'',1200,900);const cap=make('div','photo-caption');cap.append(make('span','',p.subtitle),make('span','','↗'));b.append(cap);item.append(b);photos.append(item);}
  const records=$('#v2-record-grid');
  if(records){const data=window.VINYL_CONTENT?.records||[];for(const r of data){const item=make('article','v2-record-item');item.append(imageButton(r.cover,r.title,[r.artist,r.note].filter(Boolean).join(' · '),'v2-record-image',r.width||1000,r.height||1000));item.append(make('h3','',r.title),make('p','',r.artist),make('span','record-version',r.note));if(r.source?.startsWith('https://')){const details=make('details','record-details');details.append(make('summary','','版本与来源'));const a=make('a','record-source','查看官方封面来源 ↗');a.href=r.source;a.target='_blank';a.rel='noopener noreferrer';details.append(make('p','',r.identification||r.note),a);item.append(details);}records.append(item);}$('#v2-record-count').textContent=data.length+' 张唱片';if(window.VINYL_CONTENT?.pending){const item=make('article','record-pending');item.append(make('strong','','下一张，正在核对。'),make('p','','黑白笑脸封面的专辑名与版本待确认。'));records.append(item);}}
  const track=$('#v2-card-track');
  if(track){fetch('collection-cards.json?v=collection-seven-20261002').then(r=>{if(!r.ok)throw Error('Card data unavailable');return r.json();}).then(cards=>{track.replaceChildren();for(const c of cards){const item=make('article','v2-card-item');let src=c.previewImage||c.image;let kind=c.previewImage?'AI 增强预览':'高清实拍';const b=imageButton(src,c.title,kind+' · '+c.subset+' · '+c.cardNumber,'v2-card-image',c.imageDimensions?.[0],c.imageDimensions?.[1]);const label=make('span','image-label',kind);label.hidden=!c.previewImage;b.append(label);item.append(b);if(c.previewImage){const toggles=make('div','card-toggles');for(const [image,text] of [[c.previewImage,'清晰预览'],[c.image,'高清实拍']]){const t=make('button','',text);t.type='button';t.setAttribute('aria-pressed',String(image===src));t.addEventListener('click',()=>{src=image;kind=image===c.previewImage?'AI 增强预览':'高清实拍';b.querySelector('img').src=src;b.dataset.src=src;b.dataset.caption=kind+' · '+c.subset+' · '+c.cardNumber;label.textContent=kind;label.hidden=image!==c.previewImage;toggles.querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===t)));});toggles.append(t);}item.append(toggles);}item.append(make('h3','',c.title));const details=make('details','card-details');details.append(make('summary','','查看卡牌资料'),make('p','card-meta',c.cardNumber+' / '+c.subset),make('p','',c.description));if(c.note)details.append(make('p','',c.note));item.append(details);track.append(item);}$('#v2-card-count').textContent=cards.length+' 张卡牌';settleInitialAnchor();}).catch(()=>{const status=$('#v2-card-status');if(status){status.textContent='卡册暂时没打开。';const retry=make('button','outline-button','重新打开');retry.addEventListener('click',()=>location.reload());track.append(retry);}});document.querySelectorAll('[data-card-scroll]').forEach(b=>b.addEventListener('click',()=>track.scrollBy({left:track.clientWidth*Number(b.dataset.cardScroll)*.85,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})));}
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  if(!reduced&&'IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target);}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(n=>observer.observe(n));document.body.classList.add('motion-ready');}
  const header=$('.v2-header');if(header){const sections=[...document.querySelectorAll('.v2-intro,.v2-collections,.v2-footer')];let frame;function update(){frame=null;const dark=sections.some(n=>{const r=n.getBoundingClientRect();return r.top<70&&r.bottom>70;});header.classList.toggle('is-dark',dark);}addEventListener('scroll',()=>{if(!frame)frame=requestAnimationFrame(update);},{passive:true});update();}
})();
